syntax = "proto3";

package tieba.GeneralTabList;

option java_package = "com.huanchengfly.tieba.post.api.models.protos.GeneralTabList";

import "App.proto";
import "SortOption.proto";
import "ThreadInfo.proto";
import "User.proto";

message GeneralTabListResponseData {
    repeated ThreadInfo general_list = 1;
    int32 has_more = 2;
    repeated User user_list = 3;
    int32 new_thread_num = 6;
    int32 sort_type = 7;
    repeated SortOption sort_option = 9;
    repeated App app_list = 10;
    int32 ad_show_select = 11;
    string ad_sample_map_key = 13;
}
