package com.huanchengfly.tieba.post.ui.page.settings.theme

import android.content.Context
import android.os.Build
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.util.fastFirst
import androidx.compose.ui.util.fastFirstOrNull
import androidx.lifecycle.viewModelScope
import com.google.android.material.color.utilities.Variant
import com.huanchengfly.tieba.post.arch.BaseStateViewModel
import com.huanchengfly.tieba.post.arch.stateInViewModel
import com.huanchengfly.tieba.post.repository.user.Settings
import com.huanchengfly.tieba.post.repository.user.SettingsRepository
import com.huanchengfly.tieba.post.theme.TiebaBlue
import com.huanchengfly.tieba.post.theme.colorscheme.BlueColorScheme
import com.huanchengfly.tieba.post.theme.colorscheme.GreenColorScheme
import com.huanchengfly.tieba.post.theme.colorscheme.OrangeColorScheme
import com.huanchengfly.tieba.post.theme.colorscheme.PinkColorScheme
import com.huanchengfly.tieba.post.theme.colorscheme.PurpleColorScheme
import com.huanchengfly.tieba.post.theme.colorscheme.monetColorScheme
import com.huanchengfly.tieba.post.ui.models.settings.Theme
import com.huanchengfly.tieba.post.ui.models.settings.ThemeSettings
import com.huanchengfly.tieba.post.ui.page.settings.theme.AppThemeViewModel.Companion.getBuiltInThemes
import com.huanchengfly.tieba.post.utils.extension.set
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import javax.inject.Inject

/**
 * UiState for the AppTheme
 *
 * @param pickedVariant current picked variant theme
 * @param pickedBuiltInTheme current picked built-in theme
 * @param builtInThemes list of built-in themes, generated by [getBuiltInThemes]
 * @param variantThemes list of [VariantTheme], share the same seed color
 */
@Immutable
/* data */class ThemeUiState(
    val pickedVariant: VariantTheme? = null,
    val pickedBuiltInTheme: BuiltInTheme? = null,
    val savingTheme: Boolean = false,
    val builtInThemes: List<BuiltInTheme> = emptyList(),
    val variantThemes: List<VariantTheme> = emptyList(),
) {

    fun copy(
        pickedVariant: VariantTheme? = this.pickedVariant,
        pickedBuiltInTheme: BuiltInTheme? = this.pickedBuiltInTheme,
        savingTheme: Boolean = this.savingTheme,
        builtInThemes: List<BuiltInTheme> = this.builtInThemes,
        variantThemes: List<VariantTheme> = this.variantThemes
    ) = ThemeUiState(
        pickedVariant = pickedVariant,
        pickedBuiltInTheme = pickedBuiltInTheme,
        savingTheme = savingTheme,
        builtInThemes = builtInThemes,
        variantThemes = variantThemes
    )
}

@HiltViewModel
class AppThemeViewModel @Inject constructor(
    @ApplicationContext val context: Context,
    settingsRepository: SettingsRepository
) : BaseStateViewModel<ThemeUiState>() {

    private val themeSettings: Settings<ThemeSettings> = settingsRepository.themeSettings

    /**
     * Whether or not user modified custom theme
     * */
    val isCustomThemeChanged: StateFlow<Boolean> = combine(
        flow = _uiState.map { it.pickedVariant },
        flow2 = themeSettings,
        // state.value vs settings.value
        transform = { a, b ->
            a != null && (a.color != b.customColor || a.variant != b.customVariant || b.theme != Theme.CUSTOM)
        }
    )
    .stateInViewModel(initialValue = false)

    /**
     * Whether or not user picked new built-in theme
     * */
    val isBuiltInThemeChanged: StateFlow<Boolean> = combine(
        flow = _uiState.map { it.pickedBuiltInTheme?.theme },
        flow2 = themeSettings,
        transform = { a, b -> a != null && a != b.theme }
    )
    .stateInViewModel(initialValue = false)

    private val variantList: List<Variant> by lazy { getReorderedVariants() }

    init {
        loadThemes()
    }

    override fun createInitialState(): ThemeUiState = ThemeUiState()

    private fun loadThemes() = viewModelScope.launch {
        val themeSettings = themeSettings.snapshot()
        val currentTheme = themeSettings.theme
        val customColor = themeSettings.customColor
        val customVariant = themeSettings.customVariant
        val variantThemes = generateVariantThemes(customColor ?: TiebaBlue, variantList)
        val newState = withContext(Dispatchers.Default) {
            val builtInThemes = themeSettings.getBuiltInThemes(context)
            ThemeUiState(
                pickedVariant = variantThemes.fastFirstOrNull { v -> v.variant == customVariant },
                pickedBuiltInTheme = builtInThemes.fastFirstOrNull { builtIn -> builtIn.theme == currentTheme },
                builtInThemes = builtInThemes,
                variantThemes = variantThemes
            )
        }
        _uiState.update { newState }
    }

    fun onBuiltInThemePicked(theme: BuiltInTheme) = _uiState.set { copy(pickedBuiltInTheme = theme) }

    fun onCustomColorPicked(color: Color): Unit = launchInVM {
        val variantThemes = generateVariantThemes(pickedColor = color, targetVariants = variantList)
        _uiState.update {
            val variant = it.pickedVariant?.variant ?: Variant.VIBRANT
            it.copy(
                pickedVariant = variantThemes.fastFirst { v -> v.variant == variant },
                variantThemes = variantThemes
            )
        }
    }

    fun onCustomVariantPicked(theme: VariantTheme) = _uiState.set { copy(pickedVariant = theme) }

    fun onSaveClicked(isFeatured: Boolean): Job {
        val start = System.currentTimeMillis()
        val state = _uiState.value
        require(!state.savingTheme)

        _uiState.set { copy(savingTheme = true) }
        return viewModelScope.launch {
            themeSettings.save {
                if (isFeatured) {
                    it.copy(theme = state.pickedBuiltInTheme!!.theme)
                } else {
                    val variant: VariantTheme = state.pickedVariant ?: throw NullPointerException()
                    it.copy(
                        theme = Theme.CUSTOM,
                        customColor = variant.color,
                        customVariant = variant.variant
                    )
                }
            }

            if (System.currentTimeMillis() - start <= 300) { // show loading animation longer
                delay(1200)
            }
            _uiState.update { it.copy(savingTheme = false) }
        }
    }

    // On Translucent Activity RESULT_OK, Theme changed to Theme.Translucent
    fun onTranslucentThemeChanged() = launchInVM(Dispatchers.Default) {
        val translucentTheme = themeSettings
            .map { TranslucentTheme(settings = it, context = context) }
            .first()

        _uiState.update {
            it.copy(
                pickedBuiltInTheme = translucentTheme,
                builtInThemes = it.builtInThemes.toMutableList().apply { this[0] = translucentTheme }
            )
        }
    }

    companion object {

        private fun ThemeSettings.getBuiltInThemes(context: Context): List<BuiltInTheme> {
            return Theme.entries.mapNotNull { theme ->
                when (theme) {
                    Theme.TRANSLUCENT -> TranslucentTheme(settings = this, context = context)

                    Theme.DYNAMIC -> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
                        BuiltInTheme(theme, monetColorScheme(context))
                    } else {
                        null
                    }

                    Theme.CUSTOM -> null
                    Theme.BLUE -> BuiltInTheme(theme, BlueColorScheme)
                    Theme.GREEN -> BuiltInTheme(theme, GreenColorScheme)
                    Theme.PURPLE -> BuiltInTheme(theme, PurpleColorScheme)
                    Theme.PINK -> BuiltInTheme(theme, PinkColorScheme)
                    Theme.ORANGE -> BuiltInTheme(theme, OrangeColorScheme)
                }
            }
        }

        private suspend fun generateVariantThemes(
            pickedColor: Color,
            targetVariants: List<Variant>
        ): List<VariantTheme> {
            return withContext(Dispatchers.Default) {
                targetVariants.map { VariantTheme(color = pickedColor, variant = it) }
            }
        }

        // Reordered [Variant.entries]
        private fun getReorderedVariants() = listOf(
            Variant.TONAL_SPOT,
            Variant.VIBRANT,
            Variant.EXPRESSIVE,
            Variant.FIDELITY,
            // Variant.CONTENT,
            Variant.RAINBOW,
            Variant.FRUIT_SALAD,
            Variant.NEUTRAL,
            Variant.MONOCHROME
        )
    }
}
