name: Build
on:
  workflow_dispatch:
  push:
    branches:
       - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_build:
    name: "Local tests and build"
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      commit_epoch: ${{ steps.get_version.outputs.commit_epoch }}
      version_code: ${{ steps.get_version.outputs.version_code }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup JDK 21
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' || github.event_name != 'push' }}
          cache-provider: enhanced
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run local tests
        id: localtest
        continue-on-error: true
        run: ./gradlew :app:testDebugUnitTest --no-scan --no-configuration-cache --stacktrace

      - name: Upload test report
        if: steps.localtest.outcome == 'failure'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest
          retention-days: 14
          compression-level: 9

      - name: Check test result
        continue-on-error: false
        if: steps.localtest.outcome == 'failure'
        run: echo "::warning::Local tests failed, please check test reports in artifacts" && exit 1

      - name: Build with Gradle
        if: ${{ !cancelled() }}
        run: ./gradlew assembleCi --no-configuration-cache --stacktrace

      - name: Get version
        id: get_version
        run: |
          set -e

          epoch=`git log -1 ${{ github.sha }} --format=%cd --date=unix`
          version_code=`jq -r ".elements[0].versionCode" app/build/outputs/apk/ci/output-metadata.json`
          echo "version_code=$version_code" >> "$GITHUB_OUTPUT"
          echo "commit_epoch=$epoch" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/main' && github.event_name == 'push') }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ci-artifact
          path: 'app/build/outputs/apk/ci/app-ci-unsigned.apk'
          if-no-files-found: error

      - name: Sign workflow dispatch app with release key
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        id: sign_workflow_dispatch_app
        with:
          releaseDirectory: app/build/outputs/apk/ci
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Rename workflow dispatch test APK
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          set -e
          sha=`echo ${{ github.sha }} | cut -c1-8`
          apk_name="TiebaLite.CI.test.$sha"
          mv app/build/outputs/apk/ci/app-ci-unsigned-signed.apk "${apk_name}.apk"
          echo "TEST_APK_NAME=$apk_name" >> "$GITHUB_ENV"

      - name: Upload workflow dispatch test APK
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ env.TEST_APK_NAME }}
          path: 'TiebaLite.CI.test.*.apk'
          if-no-files-found: error

  sign:
    name: "Sign and upload"
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: test_build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ci-artifact
          path: out
          merge-multiple: true

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: ci-artifact
          failOnError: false

      - name: Sign CI app
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        id: sign_app
        with:
          releaseDirectory: out
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Rename apk
        env:
          VERSION_CODE: ${{ needs.test_build.outputs.version_code }}
        run: |
          sha=`echo ${{ github.sha }} | cut -c1-8`
          apk_name="TiebaLite.CI.$VERSION_CODE.$sha"
          mv out/app-ci-unsigned-signed.apk "${apk_name}.apk"
          echo "APK_NAME=$apk_name" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.APK_NAME }}
          path: 'TiebaLite.CI.*.apk'

      - name: Print summary
        run: |
          commit_time=`TZ=Asia/Shanghai date -Iseconds -d "@${{ needs.test_build.outputs.commit_epoch }}"`
          {
            echo "### 构建完成 :zap:"
            echo ""
            echo "提交哈希 \`${{ github.sha }}\`, 创建于 $commit_time"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"
